rawDataDirectory:      "resources"
metricsDirectory:      "qc"
intermediateDirectory: "int"
resultsDirectory:      "results"
logsDirectory:         "logs"
resourcesDirectory:    "resources"
libDirectory:          "/shared/lib"
singularityDirectory:  "/shared/singularities"
referenceDirectory:    "/shared/reference"
referenceFile:         "genome.fa"
workflowSingularity:   "rakeiora-apps-20250730.sif"
varscanLib:            "VarScan.v2.4.6.jar"
